import { closeDatabaseConnection, getListingsCollection } from './db.js';

const listings = [
  {
    title: 'Machine Learning for Protein Structure Prediction',
    professor: 'Prof. Bonnie Berger',
    department: 'CSAIL',
    lab: 'Berger Lab',
    description:
      'Join our team working on applying deep learning methods to predict protein 3D structures from amino acid sequences. You will help develop and train neural network models using AlphaFold-inspired architectures, analyze prediction accuracy across protein families, and contribute to a publication-track project. The work involves working with large biological datasets and GPU-accelerated training pipelines.',
    requirements: 'Python, PyTorch, basic biology or biochemistry knowledge, 6.3900 or equivalent ML course',
    pay_or_credit: 'Both',
    posted_date: '2026-02-28',
    source_url: 'https://urop.mit.edu/listings/1001',
    contact_email: 'bberger@mit.edu',
    is_active: 1,
  },
  {
    title: 'Autonomous Drone Navigation in GPS-Denied Environments',
    professor: 'Prof. Nicholas Roy',
    department: 'AeroAstro',
    lab: 'Robust Robotics Group',
    description:
      'Work on developing SLAM (Simultaneous Localization and Mapping) algorithms for autonomous quadrotor navigation in indoor and underground environments where GPS is unavailable. The project involves implementing visual-inertial odometry, testing on real drone hardware, and benchmarking against existing approaches.',
    requirements: 'C++, ROS, linear algebra, 6.4210 or robotics experience preferred',
    pay_or_credit: 'Pay',
    posted_date: '2026-03-01',
    source_url: 'https://urop.mit.edu/listings/1002',
    contact_email: 'nickroy@mit.edu',
    is_active: 1,
  },
  {
    title: 'Quantum Error Correction Simulations',
    professor: 'Prof. Aram Harrow',
    department: 'Physics',
    lab: 'Quantum Information Group',
    description:
      'Simulate quantum error-correcting codes on classical hardware to study their fault-tolerance thresholds. You will implement surface code decoders, run Monte Carlo simulations of error channels, and analyze the results to identify optimal decoding strategies. This is a computational project with strong ties to quantum computing theory.',
    requirements: 'Python, linear algebra, quantum mechanics (8.04 or equivalent), familiarity with quantum computing concepts',
    pay_or_credit: 'Credit',
    posted_date: '2026-02-20',
    source_url: 'https://urop.mit.edu/listings/1003',
    contact_email: 'aram@mit.edu',
    is_active: 1,
  },
  {
    title: 'Natural Language Processing for Clinical Notes',
    professor: 'Prof. Regina Barzilay',
    department: 'CSAIL',
    lab: 'Machine Learning for Health',
    description:
      'Help build NLP models that extract structured medical information from unstructured clinical notes. The project aims to improve early cancer detection by identifying relevant symptoms and risk factors in patient records. You will work with transformer-based models and medical ontologies.',
    requirements: 'Python, NLP experience, 6.8610 or equivalent, comfort with large datasets',
    pay_or_credit: 'Both',
    posted_date: '2026-03-05',
    source_url: 'https://urop.mit.edu/listings/1004',
    contact_email: 'regina@csail.mit.edu',
    is_active: 1,
  },
  {
    title: 'Microfluidic Device Design for Cell Sorting',
    professor: 'Prof. Joel Voldman',
    department: 'EECS',
    lab: 'Voldman Lab',
    description:
      'Design and fabricate microfluidic devices for high-throughput single-cell sorting. The project involves CAD design of microfluidic channels, soft lithography fabrication in the cleanroom, and testing with fluorescent bead and cell samples. Great opportunity to gain cleanroom experience.',
    requirements: 'CAD software experience, chemistry or biology background, willingness to work in cleanroom',
    pay_or_credit: 'Pay',
    posted_date: '2026-02-15',
    source_url: 'https://urop.mit.edu/listings/1005',
    contact_email: 'voldman@mit.edu',
    is_active: 1,
  },
  {
    title: 'Reinforcement Learning for Robotic Manipulation',
    professor: 'Prof. Pulkit Agrawal',
    department: 'CSAIL',
    lab: 'Improbable AI Lab',
    description:
      'Develop reinforcement learning algorithms for dexterous robotic manipulation tasks. You will work on sim-to-real transfer methods, training policies in simulation (Isaac Gym/MuJoCo) and deploying them on real robotic arms. The goal is to enable robots to manipulate deformable objects like cloth and rope.',
    requirements: 'Python, PyTorch, RL basics (6.7900 or equivalent), Linux proficiency',
    pay_or_credit: 'Both',
    posted_date: '2026-03-02',
    source_url: 'https://urop.mit.edu/listings/1006',
    contact_email: 'pulkit@mit.edu',
    is_active: 1,
  },
  {
    title: 'Climate Modeling with High-Resolution Ocean Simulations',
    professor: 'Prof. Raffaele Ferrari',
    department: 'EAPS',
    lab: 'Ferrari Group',
    description:
      'Run and analyze high-resolution ocean circulation simulations to study mesoscale eddy dynamics and their role in climate. You will use the MITgcm ocean model, process terabytes of simulation output, and create visualizations of ocean currents and temperature distributions.',
    requirements: 'Python or MATLAB, basic fluid dynamics, comfort with HPC/cluster computing, 12.003 or equivalent',
    pay_or_credit: 'Pay',
    posted_date: '2026-02-18',
    source_url: 'https://urop.mit.edu/listings/1007',
    contact_email: 'rferrari@mit.edu',
    is_active: 1,
  },
  {
    title: 'Computer Vision for Autonomous Vehicles',
    professor: 'Prof. Daniela Rus',
    department: 'CSAIL',
    lab: 'Distributed Robotics Lab',
    description:
      'Work on 3D object detection and tracking algorithms for self-driving vehicles. The project involves processing LiDAR point cloud data, implementing and evaluating detection models, and testing on real-world driving datasets. You will contribute to improving the safety and reliability of autonomous driving systems.',
    requirements: 'Python, deep learning experience, familiarity with point clouds or 3D data, 6.8300 or equivalent',
    pay_or_credit: 'Both',
    posted_date: '2026-03-07',
    source_url: 'https://urop.mit.edu/listings/1008',
    contact_email: 'rus@csail.mit.edu',
    is_active: 1,
  },
  {
    title: 'CRISPR Gene Drive Modeling in Mosquito Populations',
    professor: 'Prof. Kevin Esvelt',
    department: 'Media Lab',
    lab: 'Sculpting Evolution',
    description:
      'Build computational models to predict the spread of CRISPR-based gene drives through mosquito populations. The project combines population genetics, evolutionary dynamics, and spatial modeling to assess the potential of gene drives for malaria prevention. You will develop agent-based simulations and analyze outcomes under various ecological scenarios.',
    requirements: 'Python, statistics, biology background (7.014 or 7.05), interest in computational biology',
    pay_or_credit: 'Credit',
    posted_date: '2026-02-25',
    source_url: 'https://urop.mit.edu/listings/1009',
    contact_email: 'esvelt@mit.edu',
    is_active: 1,
  },
  {
    title: 'Soft Robotics: Bio-Inspired Actuators',
    professor: 'Prof. Xuanhe Zhao',
    department: 'MechE',
    lab: 'Zhao Lab',
    description:
      'Design, fabricate, and test soft robotic actuators inspired by biological muscles. The project involves 3D printing with flexible materials, developing control systems for pneumatic actuation, and characterizing the mechanical properties of novel hydrogel composites. Ideal for someone who likes hands-on prototyping.',
    requirements: '2.001 or equivalent, 3D printing experience helpful, interest in materials science',
    pay_or_credit: 'Pay',
    posted_date: '2026-02-22',
    source_url: 'https://urop.mit.edu/listings/1010',
    contact_email: 'zhaox@mit.edu',
    is_active: 1,
  },
  {
    title: 'Cryptographic Protocol Verification',
    professor: 'Prof. Vinod Vaikuntanathan',
    department: 'CSAIL',
    lab: 'Cryptography and Information Security Group',
    description:
      'Help formally verify the security of cryptographic protocols using automated theorem provers. You will encode protocol specifications in a formal language, prove security properties, and identify potential vulnerabilities. This work bridges theoretical cryptography and practical security analysis.',
    requirements: '6.1800 or equivalent, mathematical maturity, familiarity with formal logic or proof assistants a plus',
    pay_or_credit: 'Credit',
    posted_date: '2026-03-04',
    source_url: 'https://urop.mit.edu/listings/1011',
    contact_email: 'vinodv@mit.edu',
    is_active: 1,
  },
  {
    title: 'Neural Mechanisms of Decision Making',
    professor: 'Prof. Mehrdad Jazayeri',
    department: 'BCS',
    lab: 'Jazayeri Lab',
    description:
      'Analyze neural recording data from non-human primates performing decision-making tasks. You will apply dimensionality reduction techniques, build decoding models, and develop visualizations to understand how populations of neurons represent evidence accumulation and confidence during perceptual decisions.',
    requirements: 'Python or MATLAB, statistics, 9.01 or neuroscience background, linear algebra',
    pay_or_credit: 'Both',
    posted_date: '2026-02-10',
    source_url: 'https://urop.mit.edu/listings/1012',
    contact_email: 'mjaz@mit.edu',
    is_active: 1,
  },
  {
    title: 'Sustainable Concrete with Recycled Aggregates',
    professor: 'Prof. Oral Buyukozturk',
    department: 'CEE',
    lab: 'Structural Mechanics & Materials Lab',
    description:
      'Investigate the mechanical properties of concrete made with recycled construction waste aggregates. You will cast and test specimens, perform compression and flexural strength tests, and use micro-CT imaging to analyze the microstructure. The goal is to develop sustainable building materials that reduce construction waste.',
    requirements: '1.035 or materials science background, lab experience, attention to detail',
    pay_or_credit: 'Pay',
    posted_date: '2026-01-30',
    source_url: 'https://urop.mit.edu/listings/1013',
    contact_email: 'obuyuk@mit.edu',
    is_active: 1,
  },
  {
    title: 'Generative AI for Architectural Design',
    professor: 'Prof. Caitlin Mueller',
    department: 'Architecture',
    lab: 'Digital Structures Group',
    description:
      'Explore the use of generative AI models (diffusion models, GANs) for architectural design exploration. You will train models on large datasets of building floor plans, develop interactive tools for architects to guide the generation process, and evaluate the structural feasibility of generated designs.',
    requirements: 'Python, ML experience, interest in design/architecture, familiarity with generative models',
    pay_or_credit: 'Both',
    posted_date: '2026-03-06',
    source_url: 'https://urop.mit.edu/listings/1014',
    contact_email: 'caitlinm@mit.edu',
    is_active: 1,
  },
  {
    title: 'Battery Degradation Analysis Using Electrochemical Impedance',
    professor: 'Prof. Yang Shao-Horn',
    department: 'MechE',
    lab: 'Electrochemical Energy Lab',
    description:
      'Study lithium-ion battery degradation mechanisms using electrochemical impedance spectroscopy (EIS). You will perform EIS measurements on battery cells at various states of health, fit equivalent circuit models to the data, and correlate impedance signatures with physical degradation modes like SEI growth and lithium plating.',
    requirements: 'Chemistry or materials science background, MATLAB or Python, 2.005 or electrochemistry knowledge',
    pay_or_credit: 'Pay',
    posted_date: '2026-02-12',
    source_url: 'https://urop.mit.edu/listings/1015',
    contact_email: 'shaohorn@mit.edu',
    is_active: 1,
  },
  {
    title: 'Large Language Model Alignment Research',
    professor: 'Prof. Jacob Andreas',
    department: 'CSAIL',
    lab: 'Language & Intelligence Group',
    description:
      'Investigate methods for aligning large language models with human values and intentions. You will design evaluation benchmarks, implement RLHF and constitutional AI techniques, and run experiments to measure alignment across different model architectures. The work contributes to making AI systems safer and more controllable.',
    requirements: 'Python, PyTorch, NLP or ML experience, 6.8610 or 6.7900, strong analytical skills',
    pay_or_credit: 'Both',
    posted_date: '2026-03-08',
    source_url: 'https://urop.mit.edu/listings/1016',
    contact_email: 'jda@mit.edu',
    is_active: 1,
  },
  {
    title: 'Nanoparticle Drug Delivery for Cancer Therapy',
    professor: 'Prof. Paula Hammond',
    department: 'ChemE',
    lab: 'Hammond Lab',
    description:
      'Synthesize and characterize nanoparticle drug delivery systems for targeted cancer therapy. You will prepare layer-by-layer assembled nanoparticles, perform cell viability assays, and use dynamic light scattering and electron microscopy to characterize particle size and morphology. The project aims to improve drug targeting to reduce side effects.',
    requirements: 'Chemistry or biology background, lab experience, 5.12 or 7.05, careful bench technique',
    pay_or_credit: 'Both',
    posted_date: '2026-02-08',
    source_url: 'https://urop.mit.edu/listings/1017',
    contact_email: 'hammond@mit.edu',
    is_active: 1,
  },
  {
    title: 'Probabilistic Programming for Bayesian Inference',
    professor: 'Prof. Vikash Mansinghka',
    department: 'BCS',
    lab: 'Probabilistic Computing Project',
    description:
      'Develop and test inference algorithms in the Gen probabilistic programming language. You will implement new Markov chain Monte Carlo kernels, benchmark inference quality on challenging statistical models, and contribute to the open-source Gen.jl ecosystem. The project bridges computer science, statistics, and cognitive science.',
    requirements: 'Julia or Python, probability and statistics, 6.3700 or equivalent, mathematical maturity',
    pay_or_credit: 'Credit',
    posted_date: '2026-02-27',
    source_url: 'https://urop.mit.edu/listings/1018',
    contact_email: 'vkm@mit.edu',
    is_active: 1,
  },
  {
    title: 'Fusion Reactor Plasma Diagnostics',
    professor: 'Prof. Anne White',
    department: 'NSE',
    lab: 'Plasma Science and Fusion Center',
    description:
      'Develop diagnostic tools for measuring plasma properties in the SPARC tokamak prototype. You will work on Thomson scattering optical systems, analyze spectroscopic data from plasma discharges, and help calibrate diagnostic instruments. A unique chance to work on cutting-edge fusion energy research.',
    requirements: 'Physics background (8.03 or 8.04), optics experience helpful, MATLAB or Python',
    pay_or_credit: 'Pay',
    posted_date: '2026-02-05',
    source_url: 'https://urop.mit.edu/listings/1019',
    contact_email: 'aewhite@mit.edu',
    is_active: 1,
  },
  {
    title: 'Wearable Sensors for Gait Analysis',
    professor: 'Prof. Hugh Herr',
    department: 'Media Lab',
    lab: 'Biomechatronics Group',
    description:
      'Build and test wearable IMU-based sensors for human gait analysis. You will design sensor housings, develop real-time data processing algorithms, and validate measurements against motion capture ground truth. The goal is to create affordable gait assessment tools for physical rehabilitation.',
    requirements: 'Arduino/embedded systems, Python, signal processing basics, interest in biomechanics',
    pay_or_credit: 'Both',
    posted_date: '2026-03-03',
    source_url: 'https://urop.mit.edu/listings/1020',
    contact_email: 'hherr@mit.edu',
    is_active: 1,
  },
  {
    title: 'Topology Optimization for Lightweight Structures',
    professor: 'Prof. Josephine Carstensen',
    department: 'CEE',
    lab: 'Carstensen Group',
    description:
      'Implement topology optimization algorithms to design lightweight yet strong structural components. You will write finite element analysis code, apply gradient-based optimization, and validate designs with 3D-printed prototypes and mechanical testing. Applications range from aerospace components to civil infrastructure.',
    requirements: 'MATLAB or Python, finite element basics (1.050 or 2.092), interest in structural engineering',
    pay_or_credit: 'Credit',
    posted_date: '2026-02-17',
    source_url: 'https://urop.mit.edu/listings/1021',
    contact_email: 'jvlc@mit.edu',
    is_active: 1,
  },
  {
    title: 'Single-Cell RNA Sequencing Analysis Pipeline',
    professor: 'Prof. Aviv Regev',
    department: 'Biology',
    lab: 'Klarman Cell Observatory',
    description:
      'Develop and improve computational pipelines for analyzing single-cell RNA sequencing (scRNA-seq) data. You will process raw sequencing reads, perform quality control, implement clustering and differential expression analyses, and create visualizations of cell-type landscapes. The work supports efforts to build comprehensive cell atlases of human tissues.',
    requirements: 'Python or R, statistics, 7.014 or molecular biology background, experience with data analysis',
    pay_or_credit: 'Pay',
    posted_date: '2026-03-01',
    source_url: 'https://urop.mit.edu/listings/1022',
    contact_email: 'aregev@mit.edu',
    is_active: 1,
  },
  {
    title: 'Explainable AI for Medical Imaging',
    professor: 'Prof. Polina Golland',
    department: 'CSAIL',
    lab: 'Medical Vision Group',
    description:
      'Develop interpretable deep learning models for medical image analysis. You will work on brain MRI segmentation tasks, implement attention visualization methods, and evaluate whether explanations align with clinical expertise. The project aims to increase clinician trust in AI-assisted diagnosis.',
    requirements: 'Python, PyTorch, computer vision basics, 6.8300 or equivalent, interest in healthcare AI',
    pay_or_credit: 'Both',
    posted_date: '2026-02-24',
    source_url: 'https://urop.mit.edu/listings/1023',
    contact_email: 'polina@csail.mit.edu',
    is_active: 1,
  },
  {
    title: 'Computational Fluid Dynamics for Wind Turbine Design',
    professor: 'Prof. Youssef Marzouk',
    department: 'AeroAstro',
    lab: 'Uncertainty Quantification Group',
    description:
      'Run CFD simulations of wind turbine blade aerodynamics and apply uncertainty quantification methods to robust design optimization. You will use OpenFOAM for flow simulations, implement polynomial chaos expansions for UQ, and analyze how manufacturing variability affects turbine performance.',
    requirements: 'Python or C++, fluid dynamics (16.100 or equivalent), numerical methods, HPC experience a plus',
    pay_or_credit: 'Pay',
    posted_date: '2026-02-14',
    source_url: 'https://urop.mit.edu/listings/1024',
    contact_email: 'ymarz@mit.edu',
    is_active: 1,
  },
  {
    title: 'Synthetic Biology: Engineering Microbial Biosensors',
    professor: 'Prof. Timothy Lu',
    department: 'EECS / BioE',
    lab: 'Synthetic Biology Group',
    description:
      'Engineer bacteria to detect and respond to environmental pollutants using synthetic genetic circuits. You will design genetic constructs, perform molecular cloning, characterize biosensor performance with fluorescence assays, and iterate on circuit designs to improve sensitivity and specificity.',
    requirements: 'Molecular biology lab skills, 7.014 and 7.05 or equivalent, familiarity with genetic engineering techniques',
    pay_or_credit: 'Both',
    posted_date: '2026-02-19',
    source_url: 'https://urop.mit.edu/listings/1025',
    contact_email: 'timlu@mit.edu',
    is_active: 1,
  },
  {
    title: 'Graph Neural Networks for Molecular Property Prediction',
    professor: 'Prof. Tommi Jaakkola',
    department: 'CSAIL',
    lab: 'Machine Learning Group',
    description:
      'Develop graph neural network architectures for predicting molecular properties like solubility, toxicity, and binding affinity. You will implement message-passing neural networks, train on molecular benchmark datasets, and analyze model performance to identify failure modes. The work has direct applications in drug discovery.',
    requirements: 'Python, PyTorch or JAX, graph theory basics, chemistry knowledge helpful, 6.3900 or equivalent',
    pay_or_credit: 'Credit',
    posted_date: '2026-03-06',
    source_url: 'https://urop.mit.edu/listings/1026',
    contact_email: 'tommi@csail.mit.edu',
    is_active: 1,
  },
  {
    title: 'Additive Manufacturing of Ceramic Matrix Composites',
    professor: 'Prof. A. John Hart',
    department: 'MechE',
    lab: 'Mechanosynthesis Group',
    description:
      'Explore 3D printing of ceramic matrix composites for high-temperature aerospace applications. You will prepare ceramic slurries, operate a custom binder jetting printer, sinter printed parts, and characterize mechanical properties and microstructure. This is a highly hands-on experimental project.',
    requirements: 'Materials science background (3.091 or equivalent), lab experience, interest in manufacturing',
    pay_or_credit: 'Pay',
    posted_date: '2026-01-28',
    source_url: 'https://urop.mit.edu/listings/1027',
    contact_email: 'ajhart@mit.edu',
    is_active: 1,
  },
  {
    title: 'Privacy-Preserving Machine Learning with Differential Privacy',
    professor: 'Prof. Shafi Goldwasser',
    department: 'CSAIL',
    lab: 'Theory of Computation Group',
    description:
      'Implement and evaluate differentially private training algorithms for machine learning models. You will study the privacy-accuracy tradeoff, implement DP-SGD and its variants, and benchmark on standard datasets. The project aims to enable ML on sensitive data without compromising individual privacy.',
    requirements: 'Python, ML basics, probability and statistics, 6.5620 or algorithms background',
    pay_or_credit: 'Credit',
    posted_date: '2026-02-26',
    source_url: 'https://urop.mit.edu/listings/1028',
    contact_email: 'shafi@mit.edu',
    is_active: 1,
  },
  {
    title: 'Brain-Computer Interface Signal Processing',
    professor: 'Prof. Ed Boyden',
    department: 'Media Lab / BCS',
    lab: 'Synthetic Neurobiology Group',
    description:
      'Develop signal processing and decoding algorithms for brain-computer interfaces (BCIs). You will process EEG and ECoG neural data, implement real-time spectral analysis, and build decoding models that translate neural activity into control signals. The long-term goal is to restore communication for people with paralysis.',
    requirements: 'Python or MATLAB, signal processing (6.3000 or equivalent), interest in neuroscience',
    pay_or_credit: 'Both',
    posted_date: '2026-03-02',
    source_url: 'https://urop.mit.edu/listings/1029',
    contact_email: 'esb@mit.edu',
    is_active: 1,
  },
  {
    title: 'Optimization Algorithms for Supply Chain Resilience',
    professor: 'Prof. Yossi Sheffi',
    department: 'CEE / Sloan',
    lab: 'Center for Transportation & Logistics',
    description:
      'Develop optimization models and algorithms to improve supply chain resilience against disruptions. You will formulate mixed-integer programming models, implement solution algorithms, and test on real-world supply chain network data. The research has implications for how companies prepare for events like pandemics and natural disasters.',
    requirements: 'Python or Julia, linear programming, 15.053 or 6.7200 or equivalent optimization background',
    pay_or_credit: 'Pay',
    posted_date: '2026-02-21',
    source_url: 'https://urop.mit.edu/listings/1030',
    contact_email: 'sheffi@mit.edu',
    is_active: 1,
  },
  {
    title: 'Haptic Feedback Systems for Surgical Robots',
    professor: 'Prof. Harry Asada',
    department: 'MechE',
    lab: 'd\'Arbeloff Lab',
    description:
      'Design and build haptic feedback systems for minimally invasive surgical robots. You will prototype force-sensing end effectors, develop real-time control algorithms for force rendering, and conduct user studies with surgical trainees. The goal is to restore the sense of touch during robotic surgery.',
    requirements: 'Control systems (2.004 or equivalent), embedded programming (C/C++), prototyping skills',
    pay_or_credit: 'Both',
    posted_date: '2026-02-11',
    source_url: 'https://urop.mit.edu/listings/1031',
    contact_email: 'asada@mit.edu',
    is_active: 1,
  },
  {
    title: 'Electrocatalysis for CO2 Reduction',
    professor: 'Prof. Yogesh Surendranath',
    department: 'Chemistry',
    lab: 'Surendranath Lab',
    description:
      'Investigate electrocatalytic materials for converting CO2 into useful fuels and chemicals. You will synthesize catalyst nanoparticles, perform electrochemical measurements (cyclic voltammetry, chronoamperometry), and analyze product distributions using gas chromatography. The research contributes to carbon-neutral energy technologies.',
    requirements: 'Chemistry background (5.12 or 5.60), lab experience, electrochemistry knowledge helpful',
    pay_or_credit: 'Pay',
    posted_date: '2026-02-03',
    source_url: 'https://urop.mit.edu/listings/1032',
    contact_email: 'yogi@mit.edu',
    is_active: 1,
  },
  {
    title: 'Computational Social Science: Polarization on Social Media',
    professor: 'Prof. Dean Eckles',
    department: 'Sloan / IDSS',
    lab: 'Eckles Lab',
    description:
      'Analyze large-scale social media datasets to study political polarization and information spread. You will collect and process Twitter/X data, apply network analysis methods, implement causal inference techniques, and visualize patterns of polarization. The project combines data science with social science theory.',
    requirements: 'Python or R, statistics, data analysis experience, interest in social science, 14.310 or equivalent',
    pay_or_credit: 'Credit',
    posted_date: '2026-02-16',
    source_url: 'https://urop.mit.edu/listings/1033',
    contact_email: 'deckles@mit.edu',
    is_active: 1,
  },
  {
    title: 'Perovskite Solar Cell Fabrication and Characterization',
    professor: 'Prof. Moungi Bawendi',
    department: 'Chemistry',
    lab: 'Bawendi Lab',
    description:
      'Fabricate and test perovskite solar cells in the lab. You will prepare precursor solutions, spin-coat perovskite thin films, assemble complete solar cell devices, and measure their photovoltaic performance. The project explores strategies to improve the stability and efficiency of next-generation solar cells.',
    requirements: 'Chemistry or materials science background, careful lab technique, 5.12 or 3.091',
    pay_or_credit: 'Both',
    posted_date: '2026-01-25',
    source_url: 'https://urop.mit.edu/listings/1034',
    contact_email: 'mgb@mit.edu',
    is_active: 1,
  },
  {
    title: 'Robotic Assembly in Unstructured Environments',
    professor: 'Prof. Russ Tedrake',
    department: 'CSAIL',
    lab: 'Robot Locomotion Group',
    description:
      'Develop motion planning and control algorithms for robotic assembly tasks. You will work on grasp planning, trajectory optimization, and task-and-motion planning (TAMP) to enable robots to assemble furniture from parts in cluttered environments. The project uses Drake simulation and real robot hardware.',
    requirements: 'Python or C++, linear algebra, 6.4210 or robotics experience, Drake experience a plus',
    pay_or_credit: 'Both',
    posted_date: '2026-03-05',
    source_url: 'https://urop.mit.edu/listings/1035',
    contact_email: 'russt@mit.edu',
    is_active: 1,
  },
  {
    title: 'Epidemiological Modeling of Infectious Diseases',
    professor: 'Prof. Maia Majumder',
    department: 'IDSS',
    lab: 'Computational Epidemiology Group',
    description:
      'Build compartmental and agent-based models to simulate the spread of infectious diseases. You will implement SIR/SEIR models, calibrate parameters using real-world surveillance data, and generate forecasts and scenario analyses. The work informs public health decision-making for disease outbreaks.',
    requirements: 'Python, differential equations (18.03), statistics, interest in public health',
    pay_or_credit: 'Credit',
    posted_date: '2026-02-23',
    source_url: 'https://urop.mit.edu/listings/1036',
    contact_email: 'maiamaj@mit.edu',
    is_active: 1,
  },
  {
    title: 'Acoustic Metamaterials for Sound Insulation',
    professor: 'Prof. Nicholas Fang',
    department: 'MechE',
    lab: 'Fang Lab',
    description:
      'Design and test acoustic metamaterial structures for enhanced sound insulation. You will use finite element simulations (COMSOL) to model wave propagation, fabricate prototypes using 3D printing, and measure transmission loss in an acoustic testing chamber. Applications include noise barriers and architectural acoustics.',
    requirements: 'Physics or MechE background, COMSOL or FEA experience, 2.003 or wave mechanics',
    pay_or_credit: 'Pay',
    posted_date: '2026-02-07',
    source_url: 'https://urop.mit.edu/listings/1037',
    contact_email: 'nicfang@mit.edu',
    is_active: 1,
  },
  {
    title: 'Causal Machine Learning for Economic Policy',
    professor: 'Prof. Victor Chernozhukov',
    department: 'Economics / IDSS',
    lab: 'Chernozhukov Group',
    description:
      'Apply causal machine learning methods to estimate treatment effects in economic policy evaluations. You will implement double/debiased machine learning estimators, work with large observational datasets, and evaluate the impact of policy interventions like minimum wage changes and education programs.',
    requirements: 'Python or R, econometrics or statistics, 14.310 or equivalent, mathematical maturity',
    pay_or_credit: 'Credit',
    posted_date: '2026-03-04',
    source_url: 'https://urop.mit.edu/listings/1038',
    contact_email: 'vchern@mit.edu',
    is_active: 1,
  },
  {
    title: 'Flexible Electronics for Health Monitoring',
    professor: 'Prof. Jeehwan Kim',
    department: 'MechE / MSE',
    lab: 'Kim Lab',
    description:
      'Fabricate flexible electronic devices for continuous health monitoring. You will work with thin-film deposition, photolithography, and transfer printing techniques to create stretchable sensors that can measure vital signs. The project aims to develop comfortable, long-wear health monitoring patches.',
    requirements: 'Cleanroom experience preferred, materials science or EE background, 6.2500 or equivalent',
    pay_or_credit: 'Both',
    posted_date: '2026-02-09',
    source_url: 'https://urop.mit.edu/listings/1039',
    contact_email: 'jeehwan@mit.edu',
    is_active: 1,
  },
  {
    title: 'Multi-Agent Reinforcement Learning for Traffic Control',
    professor: 'Prof. Cathy Wu',
    department: 'CEE / CSAIL',
    lab: 'Wu Lab',
    description:
      'Develop multi-agent RL algorithms for optimizing traffic signal control in urban networks. You will build simulation environments (SUMO), train cooperative RL agents, and evaluate the impact on traffic flow, emissions, and travel times. The project addresses real-world urban congestion problems.',
    requirements: 'Python, RL basics, 6.3900 or equivalent, interest in transportation/sustainability',
    pay_or_credit: 'Both',
    posted_date: '2026-03-07',
    source_url: 'https://urop.mit.edu/listings/1040',
    contact_email: 'cathywu@mit.edu',
    is_active: 1,
  },
  {
    title: 'Organic Synthesis of Pharmaceutical Intermediates',
    professor: 'Prof. Mohammad Movassaghi',
    department: 'Chemistry',
    lab: 'Movassaghi Lab',
    description:
      'Develop novel synthetic routes to complex natural product-inspired pharmaceutical intermediates. You will perform multi-step organic syntheses, purify compounds using chromatography, and characterize products with NMR and mass spectrometry. The lab emphasizes elegant, efficient synthetic strategies.',
    requirements: '5.12 (completed), organic chemistry lab experience, attention to detail, patience',
    pay_or_credit: 'Pay',
    posted_date: '2026-01-20',
    source_url: 'https://urop.mit.edu/listings/1041',
    contact_email: 'movassag@mit.edu',
    is_active: 1,
  },
  {
    title: 'Satellite Image Analysis for Urban Growth',
    professor: 'Prof. Carlo Ratti',
    department: 'Architecture / DUSP',
    lab: 'Senseable City Lab',
    description:
      'Apply computer vision and remote sensing techniques to satellite imagery to track urban growth patterns worldwide. You will process multi-temporal satellite data, train image segmentation models, and create visualizations of urban expansion over decades. The project informs sustainable urban planning.',
    requirements: 'Python, GIS or remote sensing basics, image processing, interest in urban studies',
    pay_or_credit: 'Credit',
    posted_date: '2026-02-13',
    source_url: 'https://urop.mit.edu/listings/1042',
    contact_email: 'ratti@mit.edu',
    is_active: 1,
  },
  {
    title: 'Microbiome Engineering for Gut Health',
    professor: 'Prof. Eric Alm',
    department: 'BioE / CEE',
    lab: 'Alm Lab',
    description:
      'Engineer microbial communities to promote gut health and treat inflammatory bowel disease. You will perform 16S rRNA sequencing analysis, culture anaerobic gut bacteria, design synthetic microbial consortia, and test their therapeutic effects in in-vitro gut models. Combines computation and wet-lab work.',
    requirements: 'Biology background (7.014, 7.05), microbiology experience, Python for data analysis',
    pay_or_credit: 'Both',
    posted_date: '2026-02-28',
    source_url: 'https://urop.mit.edu/listings/1043',
    contact_email: 'ejalm@mit.edu',
    is_active: 1,
  },
  {
    title: 'Formal Verification of Distributed Systems',
    professor: 'Prof. Adam Chlipala',
    department: 'CSAIL',
    lab: 'Programming Languages and Verification Group',
    description:
      'Use the Coq proof assistant to formally verify the correctness of distributed system protocols. You will encode system specifications, prove safety and liveness properties, and extract verified implementations. This rigorous approach eliminates entire classes of bugs that testing cannot catch.',
    requirements: 'Functional programming experience, 6.5120 or formal methods background, mathematical maturity',
    pay_or_credit: 'Credit',
    posted_date: '2026-02-06',
    source_url: 'https://urop.mit.edu/listings/1044',
    contact_email: 'adamc@csail.mit.edu',
    is_active: 1,
  },
  {
    title: 'High-Entropy Alloy Discovery with Machine Learning',
    professor: 'Prof. Ju Li',
    department: 'NSE / MSE',
    lab: 'Li Lab',
    description:
      'Use machine learning to accelerate the discovery of high-entropy alloys with superior mechanical properties. You will build predictive models trained on DFT calculation data, run molecular dynamics simulations, and suggest promising alloy compositions for experimental validation. The project bridges computational materials science and AI.',
    requirements: 'Python, materials science background (3.091 or equivalent), ML basics helpful',
    pay_or_credit: 'Pay',
    posted_date: '2026-03-03',
    source_url: 'https://urop.mit.edu/listings/1045',
    contact_email: 'liju@mit.edu',
    is_active: 1,
  },
  {
    title: 'Conversational AI for Mental Health Support',
    professor: 'Prof. Rosalind Picard',
    department: 'Media Lab',
    lab: 'Affective Computing Group',
    description:
      'Develop and evaluate a conversational AI system designed to provide mental health support to college students. You will fine-tune language models on counseling dialogues, implement safety guardrails, conduct user studies, and analyze conversation quality metrics. The work requires sensitivity to mental health topics and responsible AI development.',
    requirements: 'Python, NLP experience, interest in mental health, IRB experience helpful, strong ethics awareness',
    pay_or_credit: 'Both',
    posted_date: '2026-03-08',
    source_url: 'https://urop.mit.edu/listings/1046',
    contact_email: 'picard@mit.edu',
    is_active: 1,
  },
  {
    title: 'Neutron Scattering Studies of Magnetic Materials',
    professor: 'Prof. Young Lee',
    department: 'Physics',
    lab: 'Lee Group',
    description:
      'Perform neutron scattering experiments at national facilities to study exotic magnetic states in quantum materials. You will prepare single crystal samples, analyze diffraction patterns, and model magnetic structures. Travel to Oak Ridge National Lab for beam time may be involved.',
    requirements: 'Physics background (8.04, 8.044 helpful), data analysis skills, willingness to travel for experiments',
    pay_or_credit: 'Pay',
    posted_date: '2026-01-15',
    source_url: 'https://urop.mit.edu/listings/1047',
    contact_email: 'younglee@mit.edu',
    is_active: 1,
  },
  {
    title: 'Computer Architecture: RISC-V Processor Design',
    professor: 'Prof. Arvind',
    department: 'EECS',
    lab: 'Computation Structures Group',
    description:
      'Design and implement RISC-V processor extensions for accelerating machine learning workloads. You will write hardware descriptions in Bluespec SystemVerilog, simulate processor designs, synthesize for FPGA targets, and benchmark performance against baseline architectures.',
    requirements: '6.1910 or digital systems design, HDL experience (Verilog/Bluespec), computer architecture knowledge',
    pay_or_credit: 'Both',
    posted_date: '2026-02-04',
    source_url: 'https://urop.mit.edu/listings/1048',
    contact_email: 'arvind@mit.edu',
    is_active: 1,
  },
  {
    title: 'Ocean Plastic Pollution Tracking with Drifter Buoys',
    professor: 'Prof. Thomas Peacock',
    department: 'MechE',
    lab: 'Environmental Dynamics Lab',
    description:
      'Deploy and analyze data from GPS-tracked drifter buoys to study ocean plastic pollution transport. You will build low-cost drifter prototypes, process GPS trajectory data, and develop Lagrangian transport models to predict where ocean plastic accumulates. Field work at MIT Sailing Pavilion and coastal deployments.',
    requirements: 'Fluid mechanics basics, Python, electronics/Arduino, willingness to do fieldwork',
    pay_or_credit: 'Both',
    posted_date: '2026-02-20',
    source_url: 'https://urop.mit.edu/listings/1049',
    contact_email: 'tomp@mit.edu',
    is_active: 1,
  },
  {
    title: 'Algorithmic Game Theory and Mechanism Design',
    professor: 'Prof. Constantinos Daskalakis',
    department: 'EECS',
    lab: 'Theory of Computation Group',
    description:
      'Conduct theoretical and computational research on algorithmic game theory, focusing on auction design and equilibrium computation. You will implement algorithms for finding Nash equilibria, run computational experiments, and potentially contribute to theoretical proofs. Strong mathematical background required.',
    requirements: '6.1220 or algorithms, probability theory, mathematical proof experience, interest in economics/theory',
    pay_or_credit: 'Credit',
    posted_date: '2026-03-01',
    source_url: 'https://urop.mit.edu/listings/1050',
    contact_email: 'costis@csail.mit.edu',
    is_active: 1,
  },
];

async function seed() {
  const listingsCollection = await getListingsCollection();
  await listingsCollection.deleteMany({});
  await listingsCollection.insertMany(
    listings.map((listing) => ({
      ...listing,
      is_active: Boolean(listing.is_active),
      created_at: new Date(),
    }))
  );
  console.log(`Seeded ${listings.length} UROP listings.`);
}

seed()
  .catch((error) => {
    console.error('Seeding failed:', error);
    process.exitCode = 1;
  })
  .finally(async () => {
    await closeDatabaseConnection();
  });
