import dotenv from 'dotenv';
dotenv.config({ path: '../.env' });

import { connectToDatabase, closeDatabaseConnection } from './db.js';

const labs = [
  {
    name: 'Distributed Robotics Lab',
    acronym: 'DRL',
    department: 'EECS',
    pi: 'Prof. Daniela Rus',
    research_areas: ['robotics', 'autonomous systems', 'machine learning', 'self-driving vehicles', 'swarm robotics'],
    description: 'Develops distributed algorithms and systems for large networks of robots, including autonomous vehicles, programmable matter, and underwater robots.',
    website: 'https://www.csail.mit.edu/research/distributed-robotics-laboratory',
    contact_email: 'rus@csail.mit.edu',
    parent_org: 'CSAIL',
  },
  {
    name: 'Computer Science and Artificial Intelligence Laboratory',
    acronym: 'CSAIL',
    department: 'EECS',
    pi: 'Prof. Daniela Rus',
    research_areas: ['artificial intelligence', 'systems', 'theory', 'robotics', 'machine learning', 'security', 'graphics'],
    description: 'MIT\'s largest research lab, home to over 70 research groups spanning AI, systems, theory, HCI, robotics, and more.',
    website: 'https://www.csail.mit.edu',
    contact_email: null,
    parent_org: 'CSAIL',
  },
  {
    name: 'Improbable AI Lab',
    acronym: null,
    department: 'EECS',
    pi: 'Prof. Pulkit Agrawal',
    research_areas: ['reinforcement learning', 'robotics', 'manipulation', 'sim-to-real transfer', 'machine learning'],
    description: 'Develops reinforcement learning algorithms for dexterous robotic manipulation, focusing on sim-to-real transfer and learning from limited data.',
    website: 'https://improbableai.github.io',
    contact_email: 'pulkit@mit.edu',
    parent_org: 'CSAIL',
  },
  {
    name: 'Robot Locomotion Group',
    acronym: null,
    department: 'EECS',
    pi: 'Prof. Russ Tedrake',
    research_areas: ['robotics', 'motion planning', 'control', 'manipulation', 'legged locomotion'],
    description: 'Focuses on dynamics, control, and motion planning for underactuated robots using the Drake simulation framework.',
    website: 'https://groups.csail.mit.edu/locomotion/',
    contact_email: 'russt@mit.edu',
    parent_org: 'CSAIL',
  },
  {
    name: 'Language & Intelligence Group',
    acronym: null,
    department: 'EECS',
    pi: 'Prof. Jacob Andreas',
    research_areas: ['natural language processing', 'language models', 'AI alignment', 'compositional learning'],
    description: 'Studies how language can be used to build better AI systems, with work on language model alignment, grounding, and compositionality.',
    website: 'https://lingo.csail.mit.edu',
    contact_email: 'jda@mit.edu',
    parent_org: 'CSAIL',
  },
  {
    name: 'Machine Learning for Health',
    acronym: null,
    department: 'EECS',
    pi: 'Prof. Regina Barzilay',
    research_areas: ['natural language processing', 'healthcare AI', 'cancer detection', 'clinical NLP', 'drug discovery'],
    description: 'Applies machine learning and NLP to healthcare challenges including early cancer detection, clinical text analysis, and drug discovery.',
    website: 'https://www.regina.csail.mit.edu',
    contact_email: 'regina@csail.mit.edu',
    parent_org: 'CSAIL',
  },
  {
    name: 'Medical Vision Group',
    acronym: null,
    department: 'EECS',
    pi: 'Prof. Polina Golland',
    research_areas: ['medical imaging', 'computer vision', 'brain MRI', 'image segmentation', 'explainable AI'],
    description: 'Develops computational methods for medical image analysis, including brain MRI segmentation and interpretable deep learning for clinical imaging.',
    website: 'https://people.csail.mit.edu/polina/',
    contact_email: 'polina@csail.mit.edu',
    parent_org: 'CSAIL',
  },
  {
    name: 'Theory of Computation Group',
    acronym: null,
    department: 'EECS',
    pi: 'Prof. Shafi Goldwasser',
    research_areas: ['cryptography', 'privacy', 'algorithms', 'game theory', 'complexity theory'],
    description: 'Conducts research on the theoretical foundations of computer science including cryptography, algorithms, complexity, and privacy-preserving computation.',
    website: 'https://toc.csail.mit.edu',
    contact_email: null,
    parent_org: 'CSAIL',
  },
  {
    name: 'Programming Languages and Verification Group',
    acronym: 'PLV',
    department: 'EECS',
    pi: 'Prof. Adam Chlipala',
    research_areas: ['formal verification', 'programming languages', 'proof assistants', 'distributed systems', 'compilers'],
    description: 'Uses formal methods and proof assistants like Coq to verify the correctness of software systems, from distributed protocols to compilers.',
    website: 'http://plv.csail.mit.edu',
    contact_email: 'adamc@csail.mit.edu',
    parent_org: 'CSAIL',
  },
  {
    name: 'Machine Learning Group',
    acronym: null,
    department: 'EECS',
    pi: 'Prof. Tommi Jaakkola',
    research_areas: ['machine learning', 'deep learning', 'graph neural networks', 'drug discovery', 'molecular ML'],
    description: 'Develops machine learning theory and methods with applications to molecular property prediction, drug discovery, and scientific computing.',
    website: 'https://people.csail.mit.edu/tommi/',
    contact_email: 'tommi@csail.mit.edu',
    parent_org: 'CSAIL',
  },
  {
    name: 'Interactive Robotics Group',
    acronym: 'IRG',
    department: 'EECS',
    pi: 'Prof. Julie Shah',
    research_areas: ['human-robot interaction', 'collaborative robotics', 'planning', 'manufacturing', 'AI for teams'],
    description: 'Develops methods for effective human-robot collaboration in time-critical, safety-critical environments like manufacturing and healthcare.',
    website: 'https://interactive.mit.edu',
    contact_email: null,
    parent_org: 'CSAIL',
  },
  {
    name: 'Affective Computing Group',
    acronym: null,
    department: 'Media Arts and Sciences',
    pi: 'Prof. Rosalind Picard',
    research_areas: ['affective computing', 'emotion AI', 'wearable sensors', 'mental health', 'autism'],
    description: 'Pioneers the field of affective computing — building systems that recognize, interpret, and respond to human emotions for health and wellbeing.',
    website: 'https://www.media.mit.edu/groups/affective-computing/overview/',
    contact_email: 'picard@mit.edu',
    parent_org: 'Media Lab',
  },
  {
    name: 'Sculpting Evolution',
    acronym: null,
    department: 'Media Arts and Sciences',
    pi: 'Prof. Kevin Esvelt',
    research_areas: ['gene drives', 'CRISPR', 'biosecurity', 'evolutionary biology', 'synthetic biology'],
    description: 'Develops tools for safely and responsibly altering wild populations using CRISPR gene drives, with a focus on eliminating vector-borne diseases.',
    website: 'https://www.sculptingevolution.org',
    contact_email: 'esvelt@mit.edu',
    parent_org: 'Media Lab',
  },
  {
    name: 'Biomechatronics Group',
    acronym: null,
    department: 'Media Arts and Sciences',
    pi: 'Prof. Hugh Herr',
    research_areas: ['prosthetics', 'bionics', 'wearable robotics', 'biomechanics', 'neural interfaces'],
    description: 'Creates bionic limbs and wearable robots that augment human physical capability, with groundbreaking work in powered prostheses and exoskeletons.',
    website: 'https://www.media.mit.edu/groups/biomechatronics/overview/',
    contact_email: 'hherr@mit.edu',
    parent_org: 'Media Lab',
  },
  {
    name: 'Senseable City Lab',
    acronym: 'SCL',
    department: 'Architecture / DUSP',
    pi: 'Prof. Carlo Ratti',
    research_areas: ['urban computing', 'smart cities', 'remote sensing', 'data visualization', 'urban planning'],
    description: 'Studies how digital technologies are changing the way people live in and understand cities, using sensing and data analytics at urban scale.',
    website: 'https://senseable.mit.edu',
    contact_email: 'ratti@mit.edu',
    parent_org: 'Media Lab',
  },
  {
    name: 'Personal Robots Group',
    acronym: null,
    department: 'Media Arts and Sciences',
    pi: 'Prof. Cynthia Breazeal',
    research_areas: ['social robots', 'human-robot interaction', 'AI companions', 'education technology', 'child development'],
    description: 'Develops socially intelligent robots and AI companions, including Jibo, with applications in education, eldercare, and child development.',
    website: 'https://www.media.mit.edu/groups/personal-robots/overview/',
    contact_email: null,
    parent_org: 'Media Lab',
  },
  {
    name: 'Camera Culture Group',
    acronym: null,
    department: 'Media Arts and Sciences',
    pi: 'Prof. Ramesh Raskar',
    research_areas: ['computational photography', 'imaging', 'health diagnostics', 'optics', 'privacy-preserving AI'],
    description: 'Invents new imaging and sensing technologies, from femto-photography (capturing light in motion) to low-cost health diagnostic devices.',
    website: 'https://www.media.mit.edu/groups/camera-culture/overview/',
    contact_email: null,
    parent_org: 'Media Lab',
  },
  {
    name: 'Koch Institute for Integrative Cancer Research',
    acronym: 'KI',
    department: 'Biology / BioE',
    pi: 'Prof. Tyler Jacks',
    research_areas: ['cancer biology', 'drug delivery', 'immunotherapy', 'nanotechnology', 'tumor microenvironment'],
    description: 'Brings together engineers and biologists to develop new approaches to cancer detection, treatment, and prevention.',
    website: 'https://ki.mit.edu',
    contact_email: null,
    parent_org: 'Koch Institute',
  },
  {
    name: 'Hammond Lab',
    acronym: null,
    department: 'ChemE',
    pi: 'Prof. Paula Hammond',
    research_areas: ['nanoparticle drug delivery', 'cancer therapy', 'biomaterials', 'layer-by-layer assembly', 'immunoengineering'],
    description: 'Develops nanoparticle-based drug delivery systems for targeted cancer therapy using layer-by-layer assembly and electrostatic interactions.',
    website: 'https://hammondlab.mit.edu',
    contact_email: 'hammond@mit.edu',
    parent_org: 'Koch Institute',
  },
  {
    name: 'McGovern Institute for Brain Research',
    acronym: 'McGovern',
    department: 'BCS',
    pi: 'Prof. Robert Desimone',
    research_areas: ['neuroscience', 'brain imaging', 'cognitive science', 'neural circuits', 'neurodegenerative disease'],
    description: 'A leading neuroscience research center focused on understanding the brain, from molecular mechanisms to cognitive processes and brain disorders.',
    website: 'https://mcgovern.mit.edu',
    contact_email: null,
    parent_org: 'McGovern Institute',
  },
  {
    name: 'Synthetic Neurobiology Group',
    acronym: null,
    department: 'BCS / Media Lab',
    pi: 'Prof. Ed Boyden',
    research_areas: ['optogenetics', 'expansion microscopy', 'brain-computer interfaces', 'neural engineering', 'neurotechnology'],
    description: 'Develops new tools for mapping and controlling brain circuits, including optogenetics and expansion microscopy.',
    website: 'https://syntheticneurobiology.org',
    contact_email: 'esb@mit.edu',
    parent_org: 'McGovern Institute',
  },
  {
    name: 'Jazayeri Lab',
    acronym: null,
    department: 'BCS',
    pi: 'Prof. Mehrdad Jazayeri',
    research_areas: ['decision making', 'neural computation', 'motor control', 'computational neuroscience', 'timing'],
    description: 'Studies the neural basis of cognitive functions like decision-making, timing, and motor planning using electrophysiology and computational modeling.',
    website: 'https://jazlab.org',
    contact_email: 'mjaz@mit.edu',
    parent_org: 'McGovern Institute',
  },
  {
    name: 'Probabilistic Computing Project',
    acronym: 'ProbComp',
    department: 'BCS',
    pi: 'Prof. Vikash Mansinghka',
    research_areas: ['probabilistic programming', 'Bayesian inference', 'cognitive science', 'causal reasoning', 'AI'],
    description: 'Develops probabilistic programming languages and inference algorithms, bridging computer science, statistics, and cognitive science.',
    website: 'https://probcomp.csail.mit.edu',
    contact_email: 'vkm@mit.edu',
    parent_org: 'CSAIL',
  },
  {
    name: 'Plasma Science and Fusion Center',
    acronym: 'PSFC',
    department: 'NSE',
    pi: 'Prof. Dennis Whyte',
    research_areas: ['fusion energy', 'plasma physics', 'tokamak design', 'SPARC', 'superconducting magnets'],
    description: 'Conducts research on plasma science and fusion energy, including the SPARC compact tokamak project aimed at demonstrating net energy from fusion.',
    website: 'https://www.psfc.mit.edu',
    contact_email: null,
    parent_org: 'PSFC',
  },
  {
    name: 'Laboratory for Information and Decision Systems',
    acronym: 'LIDS',
    department: 'EECS',
    pi: 'Prof. John Tsitsiklis',
    research_areas: ['optimization', 'control theory', 'machine learning', 'signal processing', 'networks', 'statistics'],
    description: 'An interdisciplinary research center focusing on systems, optimization, communication, control, and statistical signal processing.',
    website: 'https://lids.mit.edu',
    contact_email: null,
    parent_org: 'LIDS',
  },
  {
    name: 'Research Laboratory of Electronics',
    acronym: 'RLE',
    department: 'EECS',
    pi: null,
    research_areas: ['quantum computing', 'photonics', 'communications', 'signal processing', 'bioelectronics', 'nanoscale systems'],
    description: 'One of MIT\'s oldest interdepartmental labs, conducting research across quantum science, photonics, communications, and biological engineering.',
    website: 'https://www.rle.mit.edu',
    contact_email: null,
    parent_org: 'RLE',
  },
  {
    name: 'Berger Lab',
    acronym: null,
    department: 'Mathematics / EECS',
    pi: 'Prof. Bonnie Berger',
    research_areas: ['computational biology', 'protein structure', 'genomics', 'deep learning', 'bioinformatics'],
    description: 'Applies mathematics and computation to problems in molecular biology, including protein structure prediction, genomics, and single-cell analysis.',
    website: 'https://people.csail.mit.edu/bab/',
    contact_email: 'bberger@mit.edu',
    parent_org: 'CSAIL',
  },
  {
    name: 'Electrochemical Energy Lab',
    acronym: 'EEL',
    department: 'MechE',
    pi: 'Prof. Yang Shao-Horn',
    research_areas: ['batteries', 'fuel cells', 'electrocatalysis', 'energy storage', 'electrochemistry'],
    description: 'Studies fundamental electrochemistry for energy storage and conversion, with work on lithium-ion batteries, solid-state batteries, and electrocatalysts.',
    website: 'https://web.mit.edu/eel/',
    contact_email: 'shaohorn@mit.edu',
    parent_org: 'Department Lab',
  },
  {
    name: 'Mechanosynthesis Group',
    acronym: null,
    department: 'MechE',
    pi: 'Prof. A. John Hart',
    research_areas: ['additive manufacturing', '3D printing', 'nanomaterials', 'carbon nanotubes', 'scalable manufacturing'],
    description: 'Develops new manufacturing processes and machines, from nanoscale to macro-scale, including 3D printing of advanced materials and carbon nanotube growth.',
    website: 'https://mechanosynthesis.mit.edu',
    contact_email: 'ajhart@mit.edu',
    parent_org: 'Department Lab',
  },
  {
    name: 'Environmental Dynamics Lab',
    acronym: 'ENDLab',
    department: 'MechE',
    pi: 'Prof. Thomas Peacock',
    research_areas: ['ocean dynamics', 'fluid mechanics', 'environmental flows', 'plastic pollution', 'internal waves'],
    description: 'Studies environmental fluid dynamics including ocean currents, internal waves, and plastic pollution transport using experiments and modeling.',
    website: 'https://endlab.mit.edu',
    contact_email: 'tomp@mit.edu',
    parent_org: 'Department Lab',
  },
  {
    name: 'Zhao Lab',
    acronym: null,
    department: 'MechE',
    pi: 'Prof. Xuanhe Zhao',
    research_areas: ['soft robotics', 'hydrogels', 'soft materials', 'bio-inspired design', '3D printing'],
    description: 'Creates soft, bio-inspired machines and materials including hydrogel robots, soft actuators, and stretchable electronics.',
    website: 'https://zhao.mit.edu',
    contact_email: 'zhaox@mit.edu',
    parent_org: 'Department Lab',
  },
  {
    name: 'Robust Robotics Group',
    acronym: null,
    department: 'AeroAstro',
    pi: 'Prof. Nicholas Roy',
    research_areas: ['autonomous navigation', 'SLAM', 'drone navigation', 'planning under uncertainty', 'human-robot interaction'],
    description: 'Develops algorithms for autonomous robot navigation in uncertain, GPS-denied environments using visual-inertial odometry and probabilistic planning.',
    website: 'https://groups.csail.mit.edu/rrg/',
    contact_email: 'nickroy@mit.edu',
    parent_org: 'CSAIL',
  },
  {
    name: 'Uncertainty Quantification Group',
    acronym: 'UQ',
    department: 'AeroAstro',
    pi: 'Prof. Youssef Marzouk',
    research_areas: ['uncertainty quantification', 'Bayesian inference', 'computational statistics', 'CFD', 'inverse problems'],
    description: 'Develops mathematical and computational methods for quantifying uncertainty in complex engineering models, from climate to aerospace systems.',
    website: 'https://uqgroup.mit.edu',
    contact_email: 'ymarz@mit.edu',
    parent_org: 'Department Lab',
  },
  {
    name: 'Digital Structures Group',
    acronym: null,
    department: 'Architecture',
    pi: 'Prof. Caitlin Mueller',
    research_areas: ['generative design', 'structural optimization', 'computational design', 'sustainable construction', 'AI for architecture'],
    description: 'Combines computational design, structural engineering, and sustainability to develop innovative architectural structures and design tools.',
    website: 'https://digitalstructures.mit.edu',
    contact_email: 'caitlinm@mit.edu',
    parent_org: 'Department Lab',
  },
  {
    name: 'Synthetic Biology Group',
    acronym: null,
    department: 'EECS / BioE',
    pi: 'Prof. Timothy Lu',
    research_areas: ['synthetic biology', 'genetic circuits', 'biosensors', 'gene therapy', 'living materials'],
    description: 'Engineers biological systems using synthetic genetic circuits, with applications in biosensing, therapeutics, and programmable living materials.',
    website: 'https://synbio.mit.edu',
    contact_email: 'timlu@mit.edu',
    parent_org: 'Department Lab',
  },
  {
    name: 'Alm Lab',
    acronym: null,
    department: 'BioE / CEE',
    pi: 'Prof. Eric Alm',
    research_areas: ['microbiome', 'metagenomics', 'gut health', 'microbial ecology', 'computational biology'],
    description: 'Studies the human microbiome using computational and experimental approaches, with applications in gut health, diagnostics, and environmental microbiology.',
    website: 'https://almlab.mit.edu',
    contact_email: 'ejalm@mit.edu',
    parent_org: 'Department Lab',
  },
  {
    name: 'Surendranath Lab',
    acronym: null,
    department: 'Chemistry',
    pi: 'Prof. Yogesh Surendranath',
    research_areas: ['electrocatalysis', 'CO2 reduction', 'renewable energy', 'electrochemistry', 'catalyst design'],
    description: 'Designs electrocatalytic materials for sustainable energy transformations, including CO2 reduction to fuels and nitrogen fixation.',
    website: 'https://surendranathgroup.mit.edu',
    contact_email: 'yogi@mit.edu',
    parent_org: 'Department Lab',
  },
  {
    name: 'Bawendi Lab',
    acronym: null,
    department: 'Chemistry',
    pi: 'Prof. Moungi Bawendi',
    research_areas: ['quantum dots', 'nanomaterials', 'solar cells', 'perovskites', 'semiconductor nanocrystals'],
    description: 'Pioneered the synthesis of quantum dots (Nobel Prize in Chemistry 2023). Current work spans perovskite solar cells, bio-imaging, and display technology.',
    website: 'https://nanocluster.mit.edu',
    contact_email: 'mgb@mit.edu',
    parent_org: 'Department Lab',
  },
  {
    name: 'Center for Transportation & Logistics',
    acronym: 'CTL',
    department: 'CEE / Sloan',
    pi: 'Prof. Yossi Sheffi',
    research_areas: ['supply chain', 'logistics', 'optimization', 'resilience', 'transportation systems'],
    description: 'A global leader in supply chain and logistics research, developing optimization models and strategies for resilient, efficient transportation systems.',
    website: 'https://ctl.mit.edu',
    contact_email: 'sheffi@mit.edu',
    parent_org: 'Department Lab',
  },
  {
    name: 'Wu Lab',
    acronym: null,
    department: 'CEE / CSAIL',
    pi: 'Prof. Cathy Wu',
    research_areas: ['traffic control', 'multi-agent RL', 'transportation', 'autonomous vehicles', 'reinforcement learning'],
    description: 'Applies multi-agent reinforcement learning and optimization to improve urban traffic flow, reduce emissions, and design better transportation networks.',
    website: 'https://www.cathywu.net',
    contact_email: 'cathywu@mit.edu',
    parent_org: 'CSAIL',
  },
  {
    name: 'Computation Structures Group',
    acronym: 'CSG',
    department: 'EECS',
    pi: 'Prof. Arvind',
    research_areas: ['computer architecture', 'RISC-V', 'FPGA', 'hardware design', 'accelerators'],
    description: 'Designs novel computer architectures and hardware description languages, with current focus on RISC-V processor extensions and ML hardware accelerators.',
    website: 'https://csg.csail.mit.edu',
    contact_email: 'arvind@mit.edu',
    parent_org: 'CSAIL',
  },
  {
    name: 'Eckles Lab',
    acronym: null,
    department: 'Sloan / IDSS',
    pi: 'Prof. Dean Eckles',
    research_areas: ['computational social science', 'causal inference', 'social networks', 'political polarization', 'A/B testing'],
    description: 'Combines data science and social science to study how social networks shape information spread, political polarization, and human behavior.',
    website: 'https://www.deaneckles.com',
    contact_email: 'deckles@mit.edu',
    parent_org: 'Department Lab',
  },
  {
    name: 'Chernozhukov Group',
    acronym: null,
    department: 'Economics / IDSS',
    pi: 'Prof. Victor Chernozhukov',
    research_areas: ['causal machine learning', 'econometrics', 'treatment effects', 'high-dimensional statistics', 'policy evaluation'],
    description: 'Develops causal machine learning methods for estimating treatment effects and evaluating economic policies using high-dimensional data.',
    website: 'https://www.mit.edu/~vchern/',
    contact_email: 'vchern@mit.edu',
    parent_org: 'Department Lab',
  },
  {
    name: 'Computational Epidemiology Group',
    acronym: null,
    department: 'IDSS',
    pi: 'Prof. Maia Majumder',
    research_areas: ['epidemiology', 'disease modeling', 'public health', 'infectious disease', 'data science'],
    description: 'Builds computational models to simulate infectious disease spread, calibrate with real-world surveillance data, and inform public health policy.',
    website: 'https://www.maimajumder.com',
    contact_email: 'maiamaj@mit.edu',
    parent_org: 'Department Lab',
  },
  {
    name: 'Kim Lab',
    acronym: null,
    department: 'MechE / MSE',
    pi: 'Prof. Jeehwan Kim',
    research_areas: ['flexible electronics', 'thin films', 'health monitoring', 'wearable devices', 'semiconductor manufacturing'],
    description: 'Develops advanced thin-film growth and transfer techniques for flexible electronics, wearable health monitors, and next-generation semiconductor devices.',
    website: 'https://kimgroup.mit.edu',
    contact_email: 'jeehwan@mit.edu',
    parent_org: 'Department Lab',
  },
  {
    name: 'Li Lab',
    acronym: null,
    department: 'NSE / MSE',
    pi: 'Prof. Ju Li',
    research_areas: ['materials science', 'high-entropy alloys', 'molecular dynamics', 'machine learning', 'energy materials'],
    description: 'Uses computational methods and machine learning to discover and design new materials, from high-entropy alloys to energy storage materials.',
    website: 'https://liju.mit.edu',
    contact_email: 'liju@mit.edu',
    parent_org: 'Department Lab',
  },
  {
    name: 'Quantum Information Group',
    acronym: null,
    department: 'Physics',
    pi: 'Prof. Aram Harrow',
    research_areas: ['quantum computing', 'quantum error correction', 'quantum information theory', 'quantum algorithms'],
    description: 'Studies the theory of quantum computation and quantum information, including error correction codes, quantum algorithms, and computational complexity.',
    website: 'https://www.mit.edu/~aram/',
    contact_email: 'aram@mit.edu',
    parent_org: 'Department Lab',
  },
  {
    name: 'Ferrari Group',
    acronym: null,
    department: 'EAPS',
    pi: 'Prof. Raffaele Ferrari',
    research_areas: ['ocean circulation', 'climate modeling', 'mesoscale eddies', 'geophysical fluid dynamics', 'ocean-atmosphere interaction'],
    description: 'Studies ocean circulation and its role in climate, using high-resolution simulations to understand turbulent mixing and heat transport in the ocean.',
    website: 'https://ferrari.mit.edu',
    contact_email: 'rferrari@mit.edu',
    parent_org: 'Department Lab',
  },
];

async function seedLabs() {
  const db = await connectToDatabase();
  const collection = db.collection('labs');

  await collection.deleteMany({});

  const now = new Date();
  const docs = labs.map((lab) => ({
    ...lab,
    is_active: true,
    created_at: now,
    updated_at: now,
  }));

  await collection.insertMany(docs);
  console.log(`Seeded ${docs.length} MIT lab groups.`);
}

seedLabs()
  .catch((error) => {
    console.error('Lab seeding failed:', error);
    process.exitCode = 1;
  })
  .finally(async () => {
    await closeDatabaseConnection();
  });
